version: '3.8'

services:
  # PHP + Apache 容器
  web:
    build:
      context: . # 使用當前目錄中的 Dockerfile 來構建映像
    image: my-app:latest #指定建構的映象名稱，在build下會變成對指定映像建構
    ports:
      - "3080:80"
    # volumes:
      # - ./src:/var/www/html
      # - ./dist:/var/www/html
